language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
matrix:
    allow_failures:
        - php: 7.0

sudo: false

before_install:
  - cp .env.example .env

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit
