# Site Meta Data
title: Photoplacer
author: James Wigger
description: "A light weight Lumen application for embedding temporary images in a web template. Host your own stock images for use in your design & development workflow"
keywords:

# Sharing Options
twitter: "@jamesyps"
android_accent: "#008955"
google_analytics:

# Site Config
baseurl: ""
url: "http://jamesyps.github.io/Photoplacer"

# Theme Settings
hero_image: "images/preview.png"
homepage: "http://jameswigger.co.uk"
download_link: "https://github.com/Jamesyps/Photoplacer/archive/master.zip"


# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']

permalink: none

sass:
  style: :compressed
  compressed: true

gems:
  - jekyll-sitemap
